#!/usr/bin/perl
print "Content-type: text/plain\r\n\r\n";
print '<meta http-equiv="pragma" content="no-cache">';
#print '<meta http-equiv="Refresh" content="15">';
print '<Title> Recycle Volumes </title>';
print '<BODY bgcolor="#fbe995">';
print '<table>';
print '<tr>';
print '<td width="12%">';
print '&nbsp;';
print '</td>';
print '<td>';
print '<h2><font color="navy">';
print 'Recyclable Volumes';
print '</font>';
print '</h2>';
print '<a href="http://atlas.dbs.co.il/index.html" alt="Back to main menu" target="_top">';
print 'Back to main menu';
print '</a>';
print '<HR>';
print '<table align="center" border="1" cellpadding="6" cellspacing="2" bgcolor="#fef7d4">';
print '<tr>';
print '<th>';
print "Pool";
print '</th>';
print '<th>';
print "Volume";
print '</th>';
print '<th>';
print "Volume Access";
print '</th>';
print '<th>';
print "Location";
print '</th>';
print '</tr>';
open(MM, "/usr/opt/networker/bin/mminfo -q volrecycle -r pool,space,volume,space,volaccess,space,location| /bin/sort|");
while (<MM>) {
next if /\bvolume\b/;
#/(\w+\s*\w*\s*\w*\s*\w*)\t*([UN][XT]\d{6})\s+([0-9][0-9]\/[0-9][0-9]\/[0-9][0-9])\s+(\w*|'')/;
/(\w+\s*\w*\s*\w*\s*\w*)\t*([UW]\d{5}[L][2]|[UN][XT]\d{6})\s+([0-9][0-9]\/[0-9][0-9]\/[0-9][0-9])\s+(\w*|'')/;
$pool = $1;
$barcode = $2;
$volaccess=$3;
$location=$4;
print "<tr><td>$pool</td>";
print "<td>$barcode</td>";
print "<td>$volaccess</td>";
print "<td>$location</td>";
}
print '</table>';
print '<td width="12%">';
print '&nbsp;';
print '</td>';
print '</tr>';
print '</table>';